name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 22 ]

    name: Build & Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Run build
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run build
      - name: Deploy to GH Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist